[tool.pytest.ini_options]
testpaths = ["tests", "integration",]

[tool.flake8]
exclude = [".venv", "build", ".vscodelocal", "migrations"]
max-line-length = 79

[tool.black]
line-length = 79
exclude = '''
/(
    migrations
  | __pycache__
  | .git
  | .venv
  | _build
  | build
  | dist
)/
'''
